# Generated by Django 5.0.6 on 2024-06-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='podcast_covers/')),
                ('audio_file', models.FileField(upload_to='episode_audio/')),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
