# Generated by Django 5.0.6 on 2024-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episodes', '0002_category_tag_episode_category_episode_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
