# Generated by Django 5.0.6 on 2024-06-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episodes', '0003_alter_episode_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='host',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
