# Generated by Django 5.0.6 on 2024-07-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articletag",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(null=True, upload_to="article_image"),
        ),
    ]
