# Generated by Django 5.0.6 on 2024-07-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0003_host_remove_episode_host_episode_hosts"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="highlight",
            field=models.BooleanField(default=False),
        ),
    ]
